- link:
    "~/AppData/Local/Programs/Local/resources/extraResources/bin/wp-cli/bin/wp": local/bin/wp
    "~/AppData/Roaming/Local/settings-new-site-defaults.json": local/settings-new-site-defaults.json
    "~/AppData/Local/Programs/Local/resources/extraResources/lightning-services/php-7.3.5+6/bin/win64/php.ini": local/conf/php.ini
