- link:
    "~/.bashrc": local/wp-cli/bashrc
    "~/AppData/Local/Programs/Local/resources/extraResources/bin/wp-cli/bin/wp": local/bin/wp
    "~/AppData/Roaming/Local/settings-new-site-defaults.json": local/settings-new-site-defaults.json
    "~/AppData/Local/Programs/Local/resources/extraResources/lightning-services/php-7.3.5+3/bin/win32/php.ini": local/conf/php.ini

- shell:
   - [bash ./local/wp-cli/wp-completion, Downloading WP-CLI completion script]