- link:
    "~/.bashrc": shell/bashrc
    "~/.bash_profile": shell/bash_profile

- create:
    - ~/.wp-cli

- shell:
    - "bash -c 'curl -sL https://raw.githubusercontent.com/wp-cli/wp-cli/master/utils/wp-completion.bash -o ~/.wp-cli/wp-completion.bash'"
