- link:
    "~/AppData/Roaming/Code/User/snippets": vscode/snippets
    "~/AppData/Roaming/Code/User/settings.json": vscode/settings.json
    "~/AppData/Roaming/Code/User/keybindings.json": vscode/keybindings.json

- shell:
    - command: "bash -c './vscode/bin/vscode-extensions'"
      description: Installing VS Code extensions.
      stdout: true
      stderr: true
