- link:
    "~/AppData/Roaming/Code/User/snippets": vscode/snippets
    "~/AppData/Roaming/Code/User/settings.json": vscode/settings.json
    "~/AppData/Roaming/Code/User/keybindings.json": vscode/keybindings.json

- shell:
  - [code --install-extension shivapoudel.wp-extension-pack, Installing VS Code Extensions]