- link:
    "~/AppData/Roaming/Code/User/snippets": vscode/snippets
    "~/AppData/Roaming/Code/User/settings.json": vscode/settings.json
    "~/AppData/Roaming/Code/User/keybindings.json": vscode/keybindings.json

- shell:
  - [bash ./bin/vscode-extensions, Installing VS Code Extensions]
